### ISSUE TITLE
manual watt modus

### ISSUE THREAD

**Issue by weinzmi** [weinzmi/ergoFACE#10]
implement a manual watt modus.
 Idea - reuse the existing watt.py and yaml

create a manual.yaml file with only one seq:

```yaml
Prog:
  Seq1:
    Name: Manual watt 
    Description: Manual Watt training
    Watt: 25
    Duration: 3600
```
